### PR TITLE
Made url's on repository list based on the current host instead of localhost

### PR DESCRIPTION
**Pull request by endoze**
Made a two line change to the repositories.js file.  My change get's the current host and stores it in a variable for use later when writing out the clone url's for each repository.

### CODE REVIEW

**Comment by poiuytrez** [comment]
Thanks for the contribution ! I will check it this week. Let me know if you would like a free license.

**Comment by endoze** [comment]
I would love a free license.  If I come up with any more useability changes, I'll be sure to share.  I have been really impressed with this product during my testing.

**Comment by poiuytrez** [comment]
Hi, Could you send us an email using this contact form : http://gitstack.com/about/
So we will have your email address.

**Comment by endoze** [comment]
Done.

**Pull request merged**
